### ISSUE TITLE
[Help][BUG] `KeyError: 'lm_head.weight'` on loading llama 3.2

### ISSUE THREAD

**Issue by steveepreston** [keras-team/keras-hub#1920]
Trying to load llama-3.2 on TPU VM v3-8 via this:
```python
device_mesh = keras.distribution.DeviceMesh((1, 8), ["batch", "model"], devices=keras.distribution.list_devices())
layout_map = keras.distribution.LayoutMap(device_mesh)
layout_map["token_embedding/embeddings"] = ("model", None)
layout_map["decoder_block.*attention.*(query|key|value)/kernel"] = ("model", None, None)
layout_map["decoder_block.*attention_output/kernel"] = ("model", None, None)
layout_map["decoder_block.*ffw_gating.*/kernel"] = (None, "model")
layout_map["decoder_block.*ffw_linear/kernel"] = ("model", None)
model_parallel = keras.distribution.ModelParallel(layout_map=layout_map, batch_dim_name="batch")
keras.distribution.set_distribution(model_parallel)


model = keras_nlp.models.Llama3CausalLM.from_preset("meta-llama/Llama-3.2-3B-Instruct")
```
but it throws this Error:

> KeyError: 'lm_head.weight'  
  

note: i get layout_map code from [This Example](https://github.com/google/generative-ai-docs/blob/main/site/en/gemma/docs/distributed_tuning.ipynb). i don't know if problem is from `layout_map` or `Llama3CausalLM`

**Comment by Gopi-Uppari** [comment]
Hi @steveepreston,

I able to execute the code using the Gemma model, and it worked without any issues. For the Llama model, however, could you please reach out to the Llama team for further assistance? Please refer to the [Gist file](https://colab.research.google.com/gist/Gopi-Uppari/340d738ae461ac52f46edcf29e544718/distributed-tuning-with-gemma-using-keras.ipynb) for more details.

Thank you.

**Comment by steveepreston** [comment]
Thank you for attention @Gopi-Uppari

Yes, `gemma` successfully executed in my test too. (although `gemma-2-9b-it` thrown OOM on TPU).
Problem is about `llama` model.

ok, i will try to create another issue there also.

**Comment by Gopi-Uppari** [comment]
Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by steveepreston** [comment]
Problem not resolved and I've moved to PyTorch.
Maybe I'll back to follow and solve this in future. There is still no example for `Llama3CausalLM`+`XLA` in the web.

**Comment by SamanehSaadat** [comment]
Hi @steveepreston 

Variable paths in Llama are different from Gemma so the layout map that works for Gemma doesn't work for Llama (see [here](https://github.com/keras-team/keras-hub/blob/b5d0e8a179c3fc9a6aa5d9f662e54d0978a80249/keras_hub/src/models/llama/llama_backbone.py#L232-L243)). 

Recently, `get_layout_map` is added for Llama [here](https://github.com/keras-team/keras-hub/blob/b5d0e8a179c3fc9a6aa5d9f662e54d0978a80249/keras_hub/src/models/llama/llama_backbone.py#L180). So instead of specifying the layout map manually, you can use this function: `layout_map = keras_nlp.models.LlamaBackbone.get_layout_map(device_mesh)`.

We haven't added `get_layout_map` for Llama3 yet but if it has the same architecture as Llama, you can copy the layout map from [here](https://github.com/keras-team/keras-hub/blob/b5d0e8a179c3fc9a6aa5d9f662e54d0978a80249/keras_hub/src/models/llama/llama_backbone.py#L267-L294).

**Comment by steveepreston** [comment]
@SamanehSaadat Thanks for the explanation. it sounds fine.
just to confirm: is `get_layout_map()` currently available only for `LlamaBackbone` and `GemmaBackbone`?
What should we do for other models, such as `distil_bert` and `phi3` and so on?

**Comment by SamanehSaadat** [comment]
@steveepreston That's correct, it's only available for Llama and Gemma right now but we're planning to add support for all other models soon. Here is the tracking issue: https://github.com/keras-team/keras-hub/issues/1689

**Comment by steveepreston** [comment]
@SamanehSaadat Got it, thanks.
